/*
 * linking_config.h
 *
 * Created: 5/11/2023 4:50:10 PM
 *  Author: sharpel
 */ 


#ifndef USART_LINKING_H_
#define USART_LINKING_H_



 // options for internal clock speed
typedef enum EN_FCPU_SELECTION{
    FCPU1M=0,
    FCPU2M,
    FCPU4M,
    FCPU8M,

}EN_FCPU_SELECTION;

// BAUD rate options
typedef enum EN_BAUDRATE_SELECTION{
    BAUDRATE_2400=0,
    BAUDRATE_4600,
    BAUDRATE_9600,
    BAUDRATE_14400,
    

}EN_BAUDRATE_SELECTION;
/* USART MODE : 
1-USART_ASYNC_MODE
2-USART_SYNC_MODE
*/
typedef enum EN_USART_SET_MODE {
    USART_ASYNC_MODE = 0 ,
    USART_SYNC_MODE
}EN_USART_SET_MODE;            

/* USART PARITY OPTIONS :
1-USART_DIS_PARITY
2-USART_ODD_PARITY
3-USART_EVEN_PARITY
*/
typedef enum EN_USART_SET_PARITY_MODE{
    USART_DIS_PARITY = 0 ,
    USART_ODD_PARITY,
    USART_EVEN_PARITY
}EN_USART_SET_PARITY_MODE;

/* USART STOP BIT OPTIONS :
1-USART_ONE_STOP_BIT
2-USART_TWO_STOP_BITS
*/
typedef enum EN_USART_SET_STOP_BIT {
 USART_ONE_STOP_BIT = 0 ,
 USART_TWO_STOP_BITS
}EN_USART_SET_STOP_BIT;    

/* USART Data SIZE OPTIONS :
1-USART_DATA_SIZE_5
2-USART_DATA_SIZE_6
3-USART_DATA_SIZE_7
4-USART_DATA_SIZE_8
5-USART_DATA_SIZE_9
*/
typedef enum EN_DATASIZE_SELECTION{
    USART_DATA_SIZE_5=0,
    USART_DATA_SIZE_6,
    USART_DATA_SIZE_7,
    USART_DATA_SIZE_8,
    USART_DATA_SIZE_9,

}EN_DATASIZE_SELECTION;


/* USART Speed MODE :
1-USART_NORMAL_SPEED
2-USART_DOUBLE_SPEED
*/
typedef enum  EN_USART_SET_SPEED {

  USART_NORMAL_SPEED = 0,
  USART_DOUBLE_SPEED
}EN_USART_SET_SPEED;            



typedef struct ST_USART_CONF{
    EN_FCPU_SELECTION FCPU;
    EN_BAUDRATE_SELECTION BAUDRATE;
    EN_USART_SET_MODE  SETMODE;
    EN_USART_SET_PARITY_MODE PARITYMODE;
    EN_USART_SET_STOP_BIT STOPBIT;
    EN_DATASIZE_SELECTION DATASIZE;
    EN_USART_SET_SPEED SETSPEED;
}ST_USART_CONF;



#endif 